grc: Display documentation for blocks without category key
Check that the category list is not empty before accessing its first
element. Some OOT modules does not have category key and documentation
tab is left empty because of this missing check.

Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/gnuradio/grc/gui/PropsDialog.py", line 210, in update_gui
    self._update_docs_page()
  File "/usr/local/lib64/python3.7/site-packages/gnuradio/grc/gui/PropsDialog.py", line 220, in _update_docs_page
    if self._block.category[0] == "Core":
IndexError: list index out of range